import { readFile, readdir, writeFile } from 'node:fs/promises';

async function collectSourceFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const resource = new URL(`${entry.name}${entry.isDirectory() ? '/' : ''}`, directory);
    if (entry.isDirectory()) return collectSourceFiles(resource);
    return /\.(?:js|jsx)$/.test(entry.name) ? [resource] : [];
  }));
  return files.flat();
}

const sourceFiles = await collectSourceFiles(new URL('../src/', import.meta.url));
const sourceText = (await Promise.all(sourceFiles.map((file) => readFile(file, 'utf8')))).join('\n');
const iconNames = [...new Set((sourceText.match(/\bbi-[a-z0-9-]+\b/g) ?? []).map((name) => name.slice(3)))].sort();

const rules = await Promise.all(iconNames.map(async (name) => {
  const source = await readFile(new URL(`../node_modules/bootstrap-icons/icons/${name}.svg`, import.meta.url), 'utf8');
  const viewBox = source.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 16 16';
  const body = source.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1]?.trim();
  if (!body) throw new Error(`Could not parse Bootstrap icon: ${name}`);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body.replaceAll('currentColor', 'black')}</svg>`;
  const encoded = encodeURIComponent(svg).replaceAll('%20', ' ');
  return `.bi-${name}::before { --bi-icon: url("data:image/svg+xml,${encoded}"); }`;
}));

const output = `/* Generated by scripts/generate-icons.mjs from Bootstrap Icons v1.11.3 (MIT). */
.bi::before {
  content: "";
  display: inline-block;
  width: 1em;
  height: 1em;
  background-color: currentColor;
  vertical-align: -.125em;
  -webkit-mask: var(--bi-icon) center / contain no-repeat;
  mask: var(--bi-icon) center / contain no-repeat;
}

${rules.join('\n')}
`;

await writeFile(new URL('../src/icons.css', import.meta.url), output, 'utf8');
console.log(`Generated ${iconNames.length} inline SVG icon masks.`);
